language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_install:
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
script:
- grunt
# Don't run sauce tests on pull requests.
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt sl-test || false'
env:
  global:
  - secure: oY8tfLwUYuBTIWhQdVyLpo9IF2f/1CgVNiaOcbuL8UyQiK863UZM2wpA3Znr3kgGJofRf2urSskcx9/y6SOHJI7bQblwyMQ+qMaPAXnZlX0KRys6s5SBsbp35juZbhtO9841QpmS9N1d8Wct25+EfchfJpQns+Spcg0jMXsw9DU=
  - secure: JhWfP63CG8HmhrpcrK5zPvCfxoNej5Fv+2iSUs2PF7CtMbkR1zH/uAlm+q92nMpLdDl2u3/NX1aONln7xZmSc9DLIHqY1CUPQwbFVSdsPhHphZ9V/c9lA2vRLCyt7u5vGPgyk+N6EQfwEQAr1c/u1ip1btt2hKjhsFxBv+0khXI=
